language: java

services:
  - mysql

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS hello_test;'

env:
  - DATABASE=jdbc:mysql://localhost:3306/hello_test DB_USERNAME=travis DB_PASSWORD="" SPRING_DATASOURCE_DRIVERCLASSNAME=com.mysql.jdbc.Driver SPRING_DATASOURCE_URL=jdbc:mysql://localhost:3306/hello_test SPRING_DATASOURCE_USERNAME=travis SPRING_DATASOURCE_PASSWORD=""
  - DATABASE=jdbc:postgresql://localhost:3306/hello_test DB_USERNAME=travis DB_PASSWORD="" SPRING_DATASOURCE_DRIVERCLASSNAME=org.postgresql.Driver SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:3306/hello_test SPRING_DATASOURCE_USERNAME=travis SPRING_DATASOURCE_PASSWORD=""

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

notifications:
  email:
    recipients:
      - robgarcal@alum.us.es
    on_success: always
    on_failure: always
